/* ---------------- ASSET MANIFEST & LOADER ----------------
   Added at v91, roadmap 3 phase 1, empty; v92 (phase 2) filled the snd half
   from SND_B64, and v95 (phase 4) filled img completely from IMG_B64 -
   every baked sprite in every colour an army can field it in, each still
   replaceable one file at a time.

   THE RULE THIS FILE EXISTS TO ENFORCE: assets OVERRIDE, they never REPLACE.
   Every procedural painter and every synthesised voice stays exactly where it
   is. A caller asks imgAsset()/sndAsset() for a texture, and paints or
   synthesises the old way when the answer is null. Three things fall out of
   that, and all three are the point:
     - a missing or failed file degrades to the v90.2 game rather than to a hole;
     - art can be replaced ONE unit at a time, so phase 4 is 25 small steps;
     - the headless suite keeps testing the procedural path, which it must,
       because the shim has no image decoder and no WebGL context.

   WHY NOTHING HERE IS ON THE newGame() PATH. Loading is asynchronous and
   newGame() is not: it is called synchronously by hundreds of fixtures across
   the tails, and by the lobby the moment a match is agreed. So the load is
   kicked off ONCE when the page opens and simply raced against the player
   reaching the Start button - by which time it has long finished. newGame()
   never waits, never yields and never learns that assets exist. T66.C pins
   that, because the day it stops being true is the day the whole test suite
   turns asynchronous.

   NOTHING HERE IS SIM STATE. No manifest entry, load flag or decoded buffer is
   hashed or serialized, and none may ever be: two clients in a lockstep match
   can legitimately hold different assets - one of them may have failed a
   download - and the match must still agree tick for tick. An asset may decide
   what a player SEES or HEARS and must never decide what happens. */
const ASSET_MANIFEST={
 /* name -> url. snd is filled by 02c-snd-data.js and img by 02d-img-data.js,
    both with data: URLs (the game is opened from file://, where fetch() of a
    relative url is refused - see 02c's header). img keys follow what
    bakeSprites() asks for: inf_<key>_<fac>_<frame>, veh_<key>_<fac>,
    bld_<key>_<fac> - one image per sprite cell (webp today), at its box and
    supersample, generated by tools/embed_img.py from assets/img/.
    mus is filled by 02f-mus-data.js the same way, one entry per music track
    (v104); it loads through _assetSnd because a track IS a sound as far as the
    loader is concerned - bytes now, decode later, on demand. */
 img:{},
 snd:{},
 mus:{}
};
const ASSETS={img:{},snd:{},mus:{}};
let ASSETS_STATE='idle';        // idle -> loading -> ready. Client-local; never hashed.
let ASSETS_FAILED=[];           // KEYS that did not arrive (keys, not urls: a data: url is half a megabyte)
let _assetsP=null;
/* Resolves when every manifest entry has either arrived or failed - it does NOT
   reject, because a missing texture is a fallback, not an error the game should
   die of. Idempotent: called twice, the second caller gets the first promise. */
function assetsLoad(){
 if(_assetsP)return _assetsP;
 ASSETS_STATE='loading';ASSETS_FAILED=[];
 const jobs=[];
 for(const k in ASSET_MANIFEST.img)jobs.push(_assetImg(k,ASSET_MANIFEST.img[k]));
 for(const k in ASSET_MANIFEST.snd)jobs.push(_assetSnd(k,ASSET_MANIFEST.snd[k]));
 for(const k in ASSET_MANIFEST.mus)jobs.push(_assetSnd(k,ASSET_MANIFEST.mus[k],ASSETS.mus));
 _assetsP=Promise.all(jobs).then(()=>{
  ASSETS_STATE='ready';
  /* headless cannot load images (no Image constructor - and Node's global
     fetch DOES exist there, which is why the gate is Image and not fetch), so
     with a filled manifest the img entries land in ASSETS_FAILED by design -
     that is the suite exercising the fallback, not a player missing files.
     Only an environment that could have loaded them warns. */
  if(ASSETS_FAILED.length&&typeof fetch==='function'&&typeof Image==='function')console.warn('assets: '+ASSETS_FAILED.length+' missing, using the built-in fallback: '+ASSETS_FAILED.join(', '));
  return ASSETS;
 });
 return _assetsP;
}
function _assetImg(key,url){
 return new Promise(res=>{
  if(typeof Image!=='function'){ASSETS_FAILED.push(key);return res()} // headless: no decoder, and none is wanted
  const im=new Image();
  im.onload=()=>{ASSETS.img[key]=im;res()};
  im.onerror=()=>{ASSETS_FAILED.push(key);res()};
  im.src=url;
 });
}
/* Stored as raw bytes rather than a decoded AudioBuffer on purpose: decoding
   needs an AudioContext, and this project creates one only after the first user
   gesture (browsers refuse it before). sndBuf() decodes on demand and caches
   into the buf slot (v92). */
function _assetSnd(key,url,into){
 const bin=into||ASSETS.snd; // v104: music lands in ASSETS.mus, same fetch, same shape
 if(typeof fetch!=='function'){ASSETS_FAILED.push(key);return Promise.resolve()}
 return fetch(url).then(r=>r.ok?r.arrayBuffer():Promise.reject(r.status))
  .then(buf=>{bin[key]={bytes:buf,buf:null}})
  .catch(()=>{ASSETS_FAILED.push(key)});
}
/* The two lookups every future caller uses. Null means "paint/synthesise it the
   way v90.2 did", which is always a legal answer. */
function imgAsset(key){return ASSETS.img[key]||null}
function sndAsset(key){return ASSETS.snd[key]||null}
function musAsset(key){return ASSETS.mus[key]||null}
function assetsReady(){return ASSETS_STATE==='ready'}
