/* tail_v96.js - T72: roadmap 3, phase 5. Per-pixel lighting: a normal map
   for every v95 texture, a normal band drawn in register with the color
   band, and the GL band shader relighting every sprite pixel - constant
   lamp, plastic specular, and point lights collected from what is actually
   exploding, burning or firing on screen.

     A  the data: one normal map per texture, byte-equal to assets/nrm
     B  the bake: .nrm rides the cell; headless none load and nothing lights
     C  the band pass: NCTX discipline, the three blit mirrors, rotation
     D  the shader and the lights: identity on flat, vision-gated sources
     E  client-local, sim-silent

   THE CLAIM THE WHOLE PHASE RESTS ON: lighting is a MODULATION around the
   baked look, not a new look. The shader normalizes its lamp so a flat
   pixel (nm.a<.5 - every procedural fallback cell, every live-drawn part,
   every sprite whose map failed to load) comes out exactly as it went in;
   relief and gleam exist only where a normal map says the surface turns.
   So the fallback ladder never changes appearance class: no GL -> v95
   pixels via the direct band, GL without maps -> v95 pixels through the
   shader, GL with maps -> v95 plus relief. Measured in Chromium: the
   lighting-only delta concentrates entirely inside sprite silhouettes. */
'use strict';
section('T72 v96: normal maps, the normal band, and the lighting shader');

const fs72 = require('fs');

/* ---------- A: the data ---------- */
{
  section('T72.A one normal map per texture, byte-equal to assets/nrm');

  const tex = Object.keys(IMG_B64).sort(), nk = Object.keys(NRM_B64).sort();
  ok(`T72.A every texture has its normal map, and no map is an orphan (${nk.length})`,
    nk.length === tex.length && nk.every((k, i) => k === tex[i]));
  ok('T72.A the maps enter the manifest under nrm_ keys, in their own format',
    nk.every(k => (ASSET_MANIFEST.img['nrm_' + k] || '').startsWith('data:' + NRM_MIME[k] + ';base64,')));

  let bad = [], total = 0;
  for (const k of nk) {
    let buf = null;
    try { buf = Buffer.from(NRM_B64[k], 'base64'); } catch (e) { }
    if (!buf || buf.length < 256 || buf.toString('ascii', 0, 4) !== 'RIFF' || buf.toString('ascii', 8, 12) !== 'WEBP') bad.push(k);
    else total += buf.length;
  }
  ok('T72.A every map decodes from base64 and opens on the WEBP signature' + (bad.length ? ' [' + bad.slice(0, 3).join(', ') + ']' : ''),
    bad.length === 0);
  ok(`T72.A the whole set stays under a megabyte and a half (${Math.round(total / 1024)} kB)`,
    total > 200 * 1024 && total < 1536 * 1024);

  let files = [];
  try { files = fs72.readdirSync('../assets/nrm').filter(f => /\.(webp|png)$/.test(f)).sort(); } catch (e) { }
  ok(`T72.A assets/nrm holds exactly the embedded maps (${files.length} files)`,
    files.length === nk.length && files.every((f, i) => f.replace(/\.(webp|png)$/, '') === nk[i]));
  let drifted = [];
  for (const f of files) {
    if (fs72.readFileSync('../assets/nrm/' + f).toString('base64') !== NRM_B64[f.replace(/\.(webp|png)$/, '')]) drifted.push(f);
  }
  ok('T72.A every embedded map is byte-identical to its file - re-run tools/embed_img.py if not' +
    (drifted.length ? ' [' + drifted.join(', ') + ']' : ''), drifted.length === 0);
  ok('T72.A the generated file says who generates it, and names the shared-rng rule',
    fs72.readFileSync('../source/js/02e-nrm-data.js', 'utf8').indexOf('GENERATED by tools/embed_img.py') >= 0 &&
    fs72.readFileSync('../source/js/02e-nrm-data.js', 'utf8').indexOf('SAME RNG RECIPE') >= 0);
}

/* ---------- B: the bake ---------- */
{
  section('T72.B the map rides the cell, and headless nothing lights');

  const src = bakeSprites.toString();
  ok('T72.B all three bake sites attach a normal map when one loaded',
    (src.match(/imgAsset\('nrm_'\+id\)/g) || []).length === 3 &&
    (src.match(/SPR\.hasNrm=true/g) || []).length === 3);

  G = null; newGame({ map: 'backyard', mode: 'dm', diff: 'normal', fac: 'gray', opp: 3, seed: 960003 });
  ok('T72.B headless no Image exists, so no cell holds a map and the switch stays off',
    SPR.hasNrm === false && !SPR.bld.hq.gray.nrm && bandLit() === false);

  /* driven with stubs: the map canvas matches its cell, and the rotation
     cache answers something for every step without touching the original */
  const cell = SPR.veh.tank.gray;
  const nc = nrmFromImg({ width: 9, height: 9 }, cell);
  ok('T72.B nrmFromImg sizes the map canvas exactly like the cell',
    nc.width === cell.cv.width && nc.height === cell.cv.height);
  cell.nrm = nc;
  const r0 = nrmRot(cell, 0), r4 = nrmRot(cell, Math.PI / 2), r4b = nrmRot(cell, Math.PI / 2);
  ok('T72.B heading 0 is the map itself; other headings cache one variant each',
    r0 === nc && !!r4 && r4b === r4);
  delete cell.nrm; delete cell._nr;
}

/* ---------- C: the band pass ---------- */
{
  section('T72.C NCTX discipline: mirrors in register, nothing on the fallback path');

  const rc = renderCore.toString();
  ok('T72.C the band pass arms NCTX only behind bandLit(), and collects the lights',
    rc.indexOf('bandLit()') >= 0 && rc.indexOf('bandLightsCollect(cx,cy,z)') >= 0);
  ok('T72.C ...and disarms it before the merge', rc.indexOf('{NCTX=null;c.save()') >= 0);
  ok('T72.C a lit-then-unlit frame cannot haunt the shader with stale normals or lights',
    rc.indexOf('GLB.lights=[]') >= 0 && rc.indexOf('nrmCv._dirty') >= 0);

  /* the three mirrors, each reading the exact transform off the color
     context - rotation included, which is what picks the vehicle variant */
  ok('T72.C the vehicle blit mirrors through the rotation cache',
    blitVeh.toString().indexOf('NCTX.drawImage(nrmRot(cell,Math.atan2(m.b,m.a))') >= 0);
  ok('T72.C the infantry and building blits mirror their maps as-is',
    (drawUnit.toString().match(/NCTX\.setTransform\(c\.getTransform\(\)\)/g) || []).length === 1 &&
    (drawBld.toString().match(/NCTX\.setTransform\(c\.getTransform\(\)\)/g) || []).length === 1);

  REN_ERRS.clear();
  render();
  ok('T72.C a full frame renders headless with the lighting off, error-free',
    REN_ERRS.size === 0 && NCTX === null);
}

/* ---------- D: the shader and the lights ---------- */
{
  section('T72.D identity on flat pixels; only what you can see casts light');

  ok('T72.D the shader is normalized so a flat pixel is untouched by the lamp',
    GLSL_BAND.indexOf('nm.a<.5?vec3(0.,0.,1.)') >= 0 &&
    GLSL_BAND.indexOf('/(uAmb+uKd*uLdir.z)') >= 0 &&
    GLSL_BAND.indexOf('-pow(hv.z,uShin)') >= 0);
  ok('T72.D the point-light loop is bounded by the table cap',
    GLSL_BAND.indexOf('if(i>=uLn)break') >= 0 && LIGHTV.max === 10);
  ok('T72.D one tuning table feeds shader and collector both',
    ['LIGHTV.amb', 'LIGHTV.kd', 'LIGHTV.ks', 'LIGHTV.shin'].every(k => bandPresent.toString().indexOf(k) >= 0) &&
    ['LIGHTV.ex', 'LIGHTV.fire', 'LIGHTV.flash'].every(k => bandLightsCollect.toString().indexOf(k) >= 0));
  ok('T72.D the normal texture uploads WITHOUT premultiply - directions, not colors',
    /uNrm|texN/.test(bandPresent.toString()) &&
    bandPresent.toString().indexOf("gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,false);\n  gl.activeTexture(gl.TEXTURE1)") >= 0);

  /* DRIVEN: the collector reads real game state through the vision gate */
  GLB = { lights: [] };
  G = null; newGame({ map: 'backyard', mode: 'dm', diff: 'normal', fac: 'tan', opp: 3, seed: 960004, test: true });
  const hq = G.human.blds.find(b => b.key === 'hq');
  G.parts.push({ t: 'ex', x: hq.tx + 1, y: hq.ty + 1, life: .3, sc: 1 });
  const s = { kind: 'fbomb', scorch: 1, owner: null, pi: 0, cells: [], i: 9, t: 0, every: 1, burn: [{ x: hq.tx + 3, y: hq.ty + 3, until: 1e9 }], bdps: 0, gnd: 1 };
  G.strikes.push(s);
  bandLightsCollect(isoX(hq.tx + 2, hq.ty + 2) - view.width / 2, isoY(hq.tx + 2, hq.ty + 2) - view.height / 2, 1);
  ok('T72.D an explosion and a fire in vision become lights', GLB.lights.length === 2);
  ok('T72.D every source is vision-gated - light through fog would be a wallhack',
    (bandLightsCollect.toString().match(/fogAt\(/g) || []).length === 2 &&
    bandLightsCollect.toString().indexOf('visibleToHuman(u)') >= 0);
  G.parts.length = 0; G.strikes.pop(); GLB = null;
}

/* ---------- E: client-local, sim-silent ---------- */
{
  section('T72.E lighting may decide what you see, never what happens');

  G = null; newGame({ map: 'backyard', mode: 'dm', diff: 'normal', fac: 'green', opp: 3, seed: 960005 });
  for (let i = 0; i < 20; i++) update(1 / 30);
  const h = hashState(), snap = saveState();
  GLB = { lights: [] };
  bandLightsCollect(0, 0, 1);
  render();
  GLB = null;
  ok('T72.E collecting lights and rendering moves neither hash nor snapshot',
    hashState() === h && saveState() === snap);
  ok('T72.E no lighting function touches the seeded stream',
    [bandPresent, bandEnsure, bandLit, bandLightsCollect, nrmRot, nrmFromImg].every(f => f.toString().indexOf('srand') < 0));
  ok('T72.E nothing of the stage is sim state - no serializer mentions it',
    ['GLB', 'LIGHTV', 'NCTX', 'nrmCv', 'hasNrm'].every(w =>
      hashState.toString().indexOf(w) < 0 && saveState.toString().indexOf(w) < 0 && loadState.toString().indexOf(w) < 0));
}
