#!/usr/bin/env python3
"""embed_snd.py - pack assets/snd/ into source/js/02c-snd-data.js.

Reads every .mp3 in assets/snd/ and writes the SND_B64 table plus the loop
that fills ASSET_MANIFEST.snd with data: URLs. Run it whenever a file in
assets/snd/ is added, removed or replaced, then ./build.sh at the repo root.

WHY data: URLs AND NOT 'assets/snd/rifle.mp3'. The README's first instruction
is "download plastic-warfare.html and double-click it", which means the game
runs from file:// - and every modern browser refuses fetch() of a relative URL
on a file:// page. fetch() of a data: URL works everywhere, needs no folder
beside the file, and leaves the phase-1 loader completely untouched: the
manifest entry is still just a URL that _assetSnd() fetches. It also keeps
T66.A's byte-for-byte guarantee, because the data rides in an ordinary source
file through the ordinary concatenating build.

The price is size (base64 is 4/3 of the mp3 bytes, all of it in the shipped
file). That is why assets/snd/ is mp3 rather than wav - measured at v92:
362 kB of mp3 against 1,010 kB for the same takes as wav.

Standalone stdlib script: no numpy, no lame, nothing to install.
"""
import base64, os, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
SND = os.path.join(ROOT, 'assets', 'snd')
OUT = os.path.join(ROOT, 'source', 'js', '02c-snd-data.js')

HEADER = """/* ---------------- SOUND ASSET DATA ---------------- */
/* GENERATED by tools/embed_snd.py from assets/snd/ - do not edit by hand.
   To replace a sound: drop the new .mp3 into assets/snd/ under the same name,
   re-run tools/embed_snd.py, then ./build.sh at the repo root. One file at a
   time is fine; that swap path is what the override architecture is for.

   Each entry is one mp3 file, base64. The loop below turns them into data:
   URLs in ASSET_MANIFEST.snd, so the phase-1 loader fetches them exactly as
   it would fetch a file - but from inside the page itself, which is what
   keeps the game a single self-contained file that still works when opened
   from disk (fetch() of a RELATIVE url is refused on a file:// page in every
   modern browser; fetch() of a data: url is not).

   NOTHING HERE IS SIM STATE, and the headless suite never sees it: the shim
   has no fetch, so under Node every one of these stays unloaded, sndAsset()
   answers null, and every test keeps exercising the synthesis - which is the
   fallback voice a player hears if a decode ever fails. */
"""

def main():
    files = sorted(f for f in os.listdir(SND) if f.endswith('.mp3'))
    if not files:
        print('no .mp3 files in ' + SND, file=sys.stderr)
        return 1
    lines = [HEADER, 'const SND_B64={\n']
    total = 0
    for f in files:
        with open(os.path.join(SND, f), 'rb') as fh:
            data = fh.read()
        total += len(data)
        key = f[:-4]
        lines.append("'%s':'%s',\n" % (key, base64.b64encode(data).decode()))
    lines.append('};\n')
    lines.append('for(const k in SND_B64)ASSET_MANIFEST.snd[k]=\'data:audio/mpeg;base64,\'+SND_B64[k];\n')
    text = ''.join(lines)
    with open(OUT, 'w') as fh:
        fh.write(text)
    print('%s: %d sounds, %d kB mp3 -> %d kB source' % (
        os.path.relpath(OUT, ROOT), len(files), total // 1024, len(text) // 1024))
    return 0

if __name__ == '__main__':
    sys.exit(main())
