#!/usr/bin/env python3
"""embed_mus.py - pack assets/mus/ into source/js/02f-mus-data.js.

Reads the four loops cut by tools/cut_music_v104.py plus their loops.json and
writes MUS_B64 and MUS_LOOP, then the loop that fills ASSET_MANIFEST.mus with
data: URLs. Run it whenever a file in assets/mus/ changes, then ./build.sh at
the repo root.

Same shape and same reasons as embed_snd.py - read that file's header for why
this is a data: URL and not 'assets/mus/menu.mp3' (file:// refuses fetch() of a
relative url; it does not refuse a data: one, which is what keeps the game a
single file you can double-click).

WHAT IS DIFFERENT FROM THE SOUND SET. A one-shot only needs its bytes; a loop
also needs to know WHERE it loops, so MUS_LOOP carries {start,end} in seconds
per track and the victory sting carries none. Those numbers are measured by the
cutter, not typed here - assets/mus/loops.json is its output and this script
only copies it across.

The price is size, and it is the largest single thing in the game after the
textures: four tracks are ~1.2 MB of mp3 and ~1.6 MB of base64. That is why
they are mono at 96k, which is also exactly what the owner auditioned.

NOTHING HERE IS SIM STATE. The headless shim has no fetch, so under Node these
never load, musBuf() answers null and every test runs with the music silent -
which is also what a player gets if a decode fails, so the silent path is the
one the suite exercises permanently.
"""
import base64, json, os, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
MUS = os.path.join(ROOT, 'assets', 'mus')
OUT = os.path.join(ROOT, 'source', 'js', '02f-mus-data.js')

HEADER = """/* ---------------- MUSIC ASSET DATA ---------------- */
/* GENERATED by tools/embed_mus.py from assets/mus/ - do not edit by hand.
   To replace a track: re-cut it with tools/cut_music_v104.py, re-run
   tools/embed_mus.py, then ./build.sh at the repo root.

   Each entry is one mp3, base64, turned into a data: URL in ASSET_MANIFEST.mus
   below so the phase-1 loader fetches it exactly as it fetches a sound - but
   from inside the page, which is what keeps the game one self-contained file
   that still works opened from disk.

   MUS_LOOP carries the loop points, in seconds, measured by the cutter. They
   are offsets into the FILE; 03b-music.js adds the decoder's own leading
   silence (sndLead) before using them, because how much of an mp3's encoder
   padding survives decoding differs per browser - the same v92 problem the
   gunfire had, solved by the same measurement.

   The victory sting has no loop points: it plays once. */
"""


def main():
    if not os.path.isdir(MUS):
        print('no ' + MUS, file=sys.stderr)
        return 1
    meta_path = os.path.join(MUS, 'loops.json')
    if not os.path.exists(meta_path):
        print('no loops.json - run tools/cut_music_v104.py first', file=sys.stderr)
        return 1
    meta = json.load(open(meta_path))
    files = sorted(f for f in os.listdir(MUS) if f.endswith('.mp3'))
    if not files:
        print('no .mp3 files in ' + MUS, file=sys.stderr)
        return 1

    lines = [HEADER, 'const MUS_B64={\n']
    total = 0
    for f in files:
        with open(os.path.join(MUS, f), 'rb') as fh:
            data = fh.read()
        total += len(data)
        lines.append("'%s':'%s',\n" % (f[:-4], base64.b64encode(data).decode()))
    lines.append('};\n')

    loop = {}
    for f in files:
        k = f[:-4]
        m = meta.get(k)
        if not m:
            print('loops.json has no entry for ' + k, file=sys.stderr)
            return 1
        loop[k] = ({'start': m['start'], 'end': m['end']} if m.get('loop')
                   else None)
    lines.append('const MUS_LOOP=%s;\n' % json.dumps(loop, sort_keys=True))
    lines.append("for(const k in MUS_B64)ASSET_MANIFEST.mus[k]="
                 "'data:audio/mpeg;base64,'+MUS_B64[k];\n")
    text = ''.join(lines)
    with open(OUT, 'w') as fh:
        fh.write(text)
    print('%s: %d tracks, %d kB mp3 -> %d kB source' % (
        os.path.relpath(OUT, ROOT), len(files), total // 1024, len(text) // 1024))
    return 0


if __name__ == '__main__':
    sys.exit(main())
