#!/usr/bin/env python3
"""embed_img.py - pack assets/img/ into source/js/02d-img-data.js.

Reads every .webp and .png in assets/img/ and writes the IMG_B64 table plus
the loop that fills ASSET_MANIFEST.img with data: URLs (each entry keeps its
own mime, so the two formats can coexist - drop in either). Run it whenever
a file in assets/img/ is added, removed or replaced, then ./build.sh at the
repo root.

Same reasoning as tools/embed_snd.py: the game is opened from file://, where
every modern browser refuses network-style loads of relative URLs, but an
Image whose src is a data: URL decodes everywhere - so the textures ride
inside the shipped file and the phase-1 loader is untouched. One file per
sprite cell keeps the phase-4 promise: any single unit's texture can be
replaced by dropping one file in assets/img/ and re-running this script.

The key convention is the one bakeSprites() looks up:
  inf_<key>_<faction>_<frame 0..4>   an infantry walk frame
  veh_<key>_<faction>                a vehicle hull (unrotated local frame)
  bld_<key>_<faction>                a building
Each image must be the sprite's bake box at SS=3 supersample - the same
pixel size bakeCell() would produce - because cellFromImg() blits it 1:1.

v96: a second pass packs assets/nrm/ (the normal maps, same ids) into
source/js/02e-nrm-data.js as NRM_B64, entering the manifest under
'nrm_<id>'. A sprite whose normal map is missing simply lights as flat -
the override rule, one layer further in.

Standalone stdlib script: no dependencies.
"""
import base64, os, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
IMG = os.path.join(ROOT, 'assets', 'img')
NRM = os.path.join(ROOT, 'assets', 'nrm')
OUT = os.path.join(ROOT, 'source', 'js', '02d-img-data.js')
OUT_NRM = os.path.join(ROOT, 'source', 'js', '02e-nrm-data.js')
MIME = {'.png': 'image/png', '.webp': 'image/webp'}

HEADER_NRM = """/* ---------------- NORMAL MAP DATA ---------------- */
/* GENERATED by tools/embed_img.py from assets/nrm/ - do not edit by hand.
   One normal map per v95 texture, same id, rendered by tools/normal_v96.py
   from the same base renders WITH THE SAME RNG RECIPE, so the grain a pixel
   shows in color is the grain it shows in relief. Encoded n*0.5+0.5 into
   RGB (x right, y down, z out), alpha = coverage; the band lighting shader
   decodes it, and a missing or failed map lights as FLAT - which is
   pixel-for-pixel the v95 look. Manifest keys are 'nrm_' + the texture id.

   NOTHING HERE IS SIM STATE; headless none of it loads (no Image), and the
   band presents its canvas directly, so the whole suite keeps testing the
   unlit path every player without real WebGL sees. */
"""

HEADER = """/* ---------------- IMAGE ASSET DATA ---------------- */
/* GENERATED by tools/embed_img.py from assets/img/ - do not edit by hand.
   To replace a texture: drop the new .png into assets/img/ under the same
   name, re-run tools/embed_img.py, then ./build.sh at the repo root. One
   file at a time is fine; that swap path is what the override architecture
   is for.

   Each entry is one image file, base64 (IMG_MIME carries each one's own
   format, so webp and png can coexist). The loop below turns them into data:
   URLs in ASSET_MANIFEST.img, so the phase-1 loader decodes them exactly as
   it would decode a file - but from inside the page itself, which is what
   keeps the game a single self-contained file that still works when opened
   from disk (see 02c-snd-data.js for the file:// reasoning).

   NOTHING HERE IS SIM STATE, and the headless suite never sees it: the shim
   has no Image, so under Node every one of these stays unloaded, imgAsset()
   answers null, and every test keeps exercising the procedural painters -
   which are the fallback a player sees if a texture ever fails to decode. */
"""

def main():
    files = sorted(f for f in os.listdir(IMG) if os.path.splitext(f)[1] in MIME)
    if not files:
        print('no .webp/.png files in ' + IMG, file=sys.stderr)
        return 1
    keys = [os.path.splitext(f)[0] for f in files]
    if len(set(keys)) != len(keys):
        print('duplicate keys across formats in ' + IMG, file=sys.stderr)
        return 1
    b64, mime = [], []
    total = 0
    for f in files:
        with open(os.path.join(IMG, f), 'rb') as fh:
            data = fh.read()
        total += len(data)
        key, ext = os.path.splitext(f)
        b64.append("'%s':'%s',\n" % (key, base64.b64encode(data).decode()))
        mime.append("'%s':'%s',\n" % (key, MIME[ext]))
    lines = [HEADER, 'const IMG_B64={\n'] + b64 + ['};\n', 'const IMG_MIME={\n'] + mime + ['};\n']
    lines.append("for(const k in IMG_B64)ASSET_MANIFEST.img[k]='data:'+IMG_MIME[k]+';base64,'+IMG_B64[k];\n")
    with open(OUT, 'w') as fh:
        fh.write(''.join(lines))
    print('wrote %s: %d textures, %d bytes of image data' % (OUT, len(files), total))

    nfiles = sorted(f for f in os.listdir(NRM) if os.path.splitext(f)[1] in MIME) if os.path.isdir(NRM) else []
    nb64, nmime = [], []
    ntotal = 0
    for f in nfiles:
        with open(os.path.join(NRM, f), 'rb') as fh:
            data = fh.read()
        ntotal += len(data)
        key, ext = os.path.splitext(f)
        nb64.append("'%s':'%s',\n" % (key, base64.b64encode(data).decode()))
        nmime.append("'%s':'%s',\n" % (key, MIME[ext]))
    nlines = [HEADER_NRM, 'const NRM_B64={\n'] + nb64 + ['};\n', 'const NRM_MIME={\n'] + nmime + ['};\n']
    nlines.append("for(const k in NRM_B64)ASSET_MANIFEST.img['nrm_'+k]='data:'+NRM_MIME[k]+';base64,'+NRM_B64[k];\n")
    with open(OUT_NRM, 'w') as fh:
        fh.write(''.join(nlines))
    print('wrote %s: %d normal maps, %d bytes' % (OUT_NRM, len(nfiles), ntotal))
    return 0

if __name__ == '__main__':
    sys.exit(main())
